# docker-compose.yml
version: "3.8"

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    volumes:
      # Mount whatever HOST_HOME is (from .env) into /srv
      - "${HOST_HOME}:/srv"
      - ./fb_config:/config
    ports:
      - "8080:80"
    restart: unless-stopped

  ttyd:
    image: tsl0922/ttyd:latest
    container_name: ttyd
    command: ["--writable", "--port", "7681", "/bin/bash", "-l"]
    volumes:
      # Mount HOST_HOME into /home/${TTYD_USER} inside the container
      - "${HOST_HOME}:/home/${TTYD_USER}"
    ports:
      - "7681:7681"
    restart: unless-stopped

  nginx_site:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-site
    volumes:
      # This is already relative & generic
      - ./Thymoe.html:/usr/share/nginx/html/Thymoe.html:ro
    ports:
      - "80:80"
    restart: unless-stopped
