# Dockerfile (nginx)
# Build this file alongside Thymoe.html
FROM nginx:1.24-alpine

# Remove default server block
RUN rm /etc/nginx/conf.d/default.conf

# Add custom server block
RUN mkdir -p /etc/nginx/conf.d && \
    cat << 'EOF' > /etc/nginx/conf.d/default.conf
server {
    listen       80 default_server;
    listen  [::]:80 default_server;
    server_name  _;

    root   /usr/share/nginx/html;
    index  Thymoe.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
EOF

# Copy Thymoe.html into place
COPY Thymoe.html /usr/share/nginx/html/Thymoe.html

# Expose port and run
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

---

# docker-compose.yml
version: "3.8"

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    volumes:
      - /home/imperator:/srv       # expose your home directory
      - ./fb_config:/config        # persist settings & DB next to this compose file
    ports:
      - "8080:80"                  # host:container
    restart: unless-stopped

  ttyd:
    image: tsl0922/ttyd:latest
    container_name: ttyd
    command: ["--writable", "--port", "7681", "/bin/bash", "-l"]
    ports:
      - "7681:7681"
    volumes:
      - /home/imperator:/home/imperator
    restart: unless-stopped

  nginx_site:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-site
    volumes:
      - ./Thymoe.html:/nginx/Thymoe.html:ro
    ports:
      - "80:80"
    restart: unless-stopped
